using UnityEngine;

// ---------------------------------------------------------------------------
//  Surf — Unity port, step 1: the world builds itself.
//
//  The browser game has no asset files at all. Every mesh, texture and material
//  in it is generated by code when the page loads, and that was a deliberate
//  rule from the beginning. So this port keeps the same rule: there are no
//  prefabs, no models and no scene to set up. Drop this one script on one empty
//  object, press Play, and everything below is built from nothing.
//
//  This step only puts the scale on screen — camera, water, board, rider, and
//  two props whose real-world sizes are known. Nothing moves yet. The point is
//  to prove the units and the framing match the browser game before anything is
//  built on top of them.
// ---------------------------------------------------------------------------
public class SurfBoot : MonoBehaviour
{
    // ---- units ----
    // ONE UNITY UNIT IS ONE FOOT. Not one metre.
    //
    // The browser game measures everything in feet: the boards are cut to their
    // published spec sheets, and the buoys and logs they pass agree with them.
    // The game also uses no engine physics whatsoever — it carries its own
    // gravity and its own buoyancy — so Unity's assumption that a unit is a
    // metre never gets a chance to matter. Keeping feet means every tuned number
    // from the browser game copies across exactly as written, and there are many
    // hundreds of them. Converting to metres would mean multiplying all of them
    // by 0.3048 and hoping nothing was missed.
    const float RIDER_FT = 2.20f;   // how tall the rider stands
    const float BOARD_L  = 5.83f;   // a six-foot shortboard, to its spec sheet
    const float BOARD_W  = 1.42f;
    const float BOARD_T  = 0.25f;

    // Two props whose sizes were measured in the browser game and used to prove
    // the whole foot-based scale was self-consistent. If the board looks right
    // beside these, the units are right.
    const float BUOY_H   = 3.17f;
    const float LOG_L    = 5.10f;

    // ---- the ride camera ----
    // These four numbers are the framing, and they are not approximations — the
    // whole look was tuned against them. The 0.5 near plane in particular is
    // load-bearing: at 0.1 the depth buffer had so little precision left at
    // distance that surfaces which touch each other flickered.
    const float FOV = 62f, NEAR = 0.5f, FAR = 500f;
    // The browser camera sits 4.9 above the water and 11 behind, and aims at a
    // point 1.05 up and well ahead. That works out at 8.76 degrees of down-tilt.
    const float CAM_Y = 4.9f, CAM_Z = -11f, CAM_PITCH = 8.76f;

    void Awake()
    {
        BuildCamera();
        BuildSun();
        BuildWater();

        // the board, sitting on the water
        var board = Box("Board", new Vector3(BOARD_W, BOARD_T, BOARD_L),
                        new Color(0.96f, 0.55f, 0.30f));
        board.transform.position = new Vector3(0f, BOARD_T * 0.5f, 0f);

        // the rider, standing on the board. Unity's capsule is 2 units tall and
        // 1 across at scale 1, so half the height gives the feet we want.
        var rider = Prim("Rider", PrimitiveType.Capsule,
                         new Color(0.85f, 0.69f, 0.45f));
        rider.transform.localScale = new Vector3(RIDER_FT * 0.25f,
                                                 RIDER_FT * 0.5f,
                                                 RIDER_FT * 0.25f);
        rider.transform.position = new Vector3(0f, BOARD_T + RIDER_FT * 0.5f, 0f);

        // ---- the two rulers ----
        var buoy = Prim("Buoy (3.17ft)", PrimitiveType.Cylinder,
                        new Color(0.85f, 0.20f, 0.18f));
        buoy.transform.localScale = new Vector3(1.6f, BUOY_H * 0.5f, 1.6f);
        buoy.transform.position = new Vector3(-5f, BUOY_H * 0.35f, 9f);

        var log = Box("Log (5.1ft)", new Vector3(1.0f, 1.0f, LOG_L),
                      new Color(0.45f, 0.27f, 0.14f));
        log.transform.position = new Vector3(5.5f, 0.4f, 9f);

        // and say out loud what was built, so the numbers can be checked against
        // the browser game rather than eyeballed
        Debug.Log($"[Surf] 1 unit = 1 foot.  rider {RIDER_FT}ft on a {BOARD_L}ft board " +
                  $"({(RIDER_FT / BOARD_L * 100f):0}% of its length).  " +
                  $"camera {Mathf.Abs(CAM_Z)}ft back, {CAM_Y}ft up, {CAM_PITCH}deg down, {FOV}deg FOV.");
    }

    void BuildCamera()
    {
        var cam = Camera.main;
        if (cam == null)
        {
            var go = new GameObject("Main Camera");
            go.tag = "MainCamera";
            cam = go.AddComponent<Camera>();
        }
        cam.transform.position = new Vector3(0f, CAM_Y, CAM_Z);
        cam.transform.rotation = Quaternion.Euler(CAM_PITCH, 0f, 0f);
        cam.fieldOfView = FOV;
        cam.nearClipPlane = NEAR;
        cam.farClipPlane = FAR;
        cam.clearFlags = CameraClearFlags.SolidColor;
        // a plain sky for now; the browser game's graded sky comes later
        cam.backgroundColor = new Color(0.60f, 0.76f, 0.88f);
    }

    void BuildSun()
    {
        var go = new GameObject("Sun");
        var l = go.AddComponent<Light>();
        l.type = LightType.Directional;
        l.color = new Color(1.0f, 0.95f, 0.88f);
        l.intensity = 1.5f;
        go.transform.rotation = Quaternion.Euler(38f, -155f, 0f);
    }

    void BuildWater()
    {
        // Flat for now. The real thing is a subdivided mesh driven by the wave
        // function, and that is the next piece of work — but nothing can be
        // checked against it until the scale underneath is known to be right.
        var w = Prim("Water (flat, placeholder)", PrimitiveType.Plane,
                     new Color(0.09f, 0.42f, 0.62f));
        w.transform.localScale = new Vector3(40f, 1f, 40f);   // a Plane is 10 units across
        w.transform.position = Vector3.zero;
    }

    // ---- the small amount of plumbing the above needs ----

    GameObject Prim(string name, PrimitiveType type, Color c)
    {
        var go = GameObject.CreatePrimitive(type);
        go.name = name;
        go.transform.SetParent(transform, false);
        // No engine physics anywhere in this game, so the colliders Unity adds to
        // its primitives are dead weight — and worse, they invite someone to
        // later assume they are doing something.
        var col = go.GetComponent<Collider>();
        if (col != null) Destroy(col);
        go.GetComponent<Renderer>().sharedMaterial = Mat(c);
        return go;
    }

    GameObject Box(string name, Vector3 size, Color c)
    {
        var go = Prim(name, PrimitiveType.Cube, c);
        go.transform.localScale = size;
        return go;
    }

    Material Mat(Color c)
    {
        // URP's Lit shader, falling back to the built-in one so this still draws
        // something if the project was made on the wrong template.
        var sh = Shader.Find("Universal Render Pipeline/Lit");
        if (sh == null) sh = Shader.Find("Standard");
        var m = new Material(sh);
        // URP calls it _BaseColor and the built-in pipeline calls it _Color.
        if (m.HasProperty("_BaseColor")) m.SetColor("_BaseColor", c);
        if (m.HasProperty("_Color")) m.SetColor("_Color", c);
        if (m.HasProperty("_Smoothness")) m.SetFloat("_Smoothness", 0.25f);
        return m;
    }
}
